import { mkdirSync, writeFileSync } from "node:fs";
import { extractText, getDocumentProxy } from "unpdf";
import { generateCommercialProposalPdf } from "@/lib/commercialProposal/generatePdf";
import { applyGlobalDiscount } from "@/lib/commercialProposal/money";
import { buildProposalSnapshot } from "@/lib/commercialProposal/snapshot";
import { normalizeCategoryDiscounts } from "@/lib/commercialProposal/discounts";
import { CP_TEMPLATE_LT_COMMERCIAL_V2, type CommercialProposalLine } from "@/lib/commercialProposal/types";

function assert(cond: unknown, message: string) {
  if (!cond) throw new Error(message);
}

function line(
  partial: Pick<CommercialProposalLine, "category" | "label"> &
    Partial<Omit<CommercialProposalLine, "category" | "label">>,
): Omit<CommercialProposalLine, "id" | "proposal_id"> {
  return {
    catalog_item_id: partial.catalog_item_id ?? partial.label,
    sort_order: partial.sort_order ?? 1,
    base_price: partial.base_price ?? 10,
    calculated_price: partial.calculated_price ?? 10,
    final_price: partial.final_price ?? 10,
    is_manual_override: false,
    is_from_price: false,
    is_free: false,
    included: partial.included,
    currency: "EUR",
    unit: "psl.",
    ...partial,
  };
}

const catalog = [
  line({ category: "translation", label: "LT-EN", catalog_item_id: "LT-EN", sort_order: 1, base_price: 10.8, calculated_price: 10.8, final_price: 10.8 }),
  line({ category: "translation", label: "LT-RU", catalog_item_id: "LT-RU", sort_order: 2, base_price: 10.8, calculated_price: 10.8, final_price: 10.8 }),
  line({ category: "translation", label: "LT-DE", catalog_item_id: "LT-DE", sort_order: 3, base_price: 12, calculated_price: 12, final_price: 12 }),
  line({ category: "ai_translation", label: "AI-LT-EN", catalog_item_id: "AI-LT-EN", sort_order: 1, base_price: 6.48, calculated_price: 6.48, final_price: 6.48 }),
  line({ category: "ai_translation", label: "AI-LT-DE", catalog_item_id: "AI-LT-DE", sort_order: 2, base_price: 7, calculated_price: 7, final_price: 7 }),
  line({ category: "additional_service", label: "Apostille", catalog_item_id: "apostille", sort_order: 1, base_price: 25, calculated_price: 25, final_price: 25 }),
  line({ category: "additional_service", label: "Interpreting", catalog_item_id: "interpreting", sort_order: 2, base_price: 40, calculated_price: 40, final_price: 40 }),
];

const manager = {
  id: "m1",
  first_name: "Ada",
  last_name: "Vadybininkė",
  display_name: "Ada Vadybininkė",
  job_title: "Pardavimų vadybininkė",
  email: null,
  phone: null,
  avatar_url: null,
};

function snap(lines: typeof catalog, discounts = { translation: 0, ai_translation: 0, additional_service: 0 }) {
  return buildProposalSnapshot({
    proposalNumber: "CP-2026-0099",
    createdAt: "2026-08-20T00:00:00.000Z",
    generatedAt: "2026-08-20T00:00:00.000Z",
    templateVersion: CP_TEMPLATE_LT_COMMERCIAL_V2,
    discounts: normalizeCategoryDiscounts(discounts),
    client: { client_key: "c1", client_id: "c1", company_code: null, name: "Klientas" },
    salesManager: manager,
    history: [{ year: 2020, body: "Istorija.", sort_order: 1 }],
    lines,
  });
}

async function pdfText(bytes: Uint8Array, name: string) {
  mkdirSync("tmp/cp-ux", { recursive: true });
  const file = `tmp/cp-ux/${name}.pdf`;
  writeFileSync(file, Buffer.from(bytes));
  if (Buffer.from(bytes).subarray(0, 4).toString() !== "%PDF") {
    throw new Error(`${name}: generated bytes are not a PDF`);
  }
  const doc = await getDocumentProxy(new Uint8Array(bytes));
  const extracted = await extractText(doc, { mergePages: false });
  const pages = Array.isArray(extracted.text) ? extracted.text : [String(extracted.text ?? "")];
  return { text: pages.join("\n"), pages: pages.length, file };
}

const translationOnly = catalog.map((l) => ({
  ...l,
  included: l.category === "translation" && (l.catalog_item_id === "LT-EN" || l.catalog_item_id === "LT-RU"),
}));
const t2 = await pdfText(await generateCommercialProposalPdf({ snapshot: snap(translationOnly) }), "t2-translation");
assert(t2.text.includes("LT-EN") && t2.text.includes("LT-RU"), "T2 selected languages present");
assert(!t2.text.includes("LT-DE"), "T2 unused language absent");
assert(!t2.text.includes("AI-LT-EN") && !t2.text.includes("AI-LT-DE"), "T2 AI rows absent");
assert(!t2.text.includes("Apostille") && !t2.text.includes("Interpreting"), "T2 extras absent");
assert(!t2.text.includes("AI vertimas ir redagavimas"), "T2 no AI section heading");
assert(!t2.text.includes("Papildomų paslaugų įkainiai"), "T2 no extras section heading");
assert(t2.text.includes("Vertimas raštu"), "T2 translation heading present");

const aiOnly = catalog.map((l) => ({ ...l, included: l.category === "ai_translation" }));
const t3snap = snap(aiOnly);
assert(t3snap.lines.every((l) => l.category === "ai_translation"), "T3 snapshot is AI only");
const t3 = await pdfText(await generateCommercialProposalPdf({ snapshot: t3snap }), "t3-ai");
assert(t3.text.includes("AI-LT-EN") && t3.text.includes("AI vertimas ir redagavimas"), "T3 AI present");
assert(!t3.text.includes("Papildomų paslaugų įkainiai"), "T3 no extras heading");
assert(!t3.text.includes("Apostille") && !t3.text.includes("Interpreting"), "T3 extras rows absent");
assert(t3.pages <= t2.pages, "T3 page count stays compact");

const apostilleOnly = catalog.map((l) => ({ ...l, included: l.catalog_item_id === "apostille" }));
const t4 = await pdfText(await generateCommercialProposalPdf({ snapshot: snap(apostilleOnly) }), "t4-apostille");
assert(t4.text.includes("Apostille"), "T4 apostille present");
assert(!t4.text.includes("Interpreting"), "T4 unused extra absent");
assert(!t4.text.includes("LT-EN") && !t4.text.includes("AI-LT-EN"), "T4 other categories absent");
assert(t4.text.includes("Papildomų paslaugų įkainiai"), "T4 extras heading present");
assert(!t4.text.includes("LT-RU") && !t4.text.includes("LT-DE"), "T4 no other translation rows");

const discounted = catalog.map((l) => {
  const included = l.category === "translation" || l.catalog_item_id === "apostille";
  const pct = l.category === "translation" ? 10 : l.category === "additional_service" ? 15 : 0;
  const calculated = applyGlobalDiscount(l.base_price ?? 0, pct);
  return { ...l, included, calculated_price: calculated, final_price: calculated };
});
const t5snap = snap(discounted, { translation: 10, ai_translation: 0, additional_service: 15 });
assert(!t5snap.lines.some((l) => l.category === "ai_translation"), "T5 AI excluded from snapshot");
const t5 = await pdfText(await generateCommercialProposalPdf({ snapshot: t5snap }), "t5-discounts");
assert(t5.text.includes("9,72"), "T5 translation 10% shown");
assert(t5.text.includes("21,25"), "T5 apostille 15% shown");
assert(!t5.text.includes("AI-LT-EN"), "T5 excluded AI not in PDF");

const override = catalog.map((l) => {
  if (l.catalog_item_id !== "LT-EN") {
    return { ...l, included: l.category === "translation" && l.catalog_item_id === "LT-EN" };
  }
  return {
    ...l,
    included: true,
    calculated_price: 9.72,
    final_price: 9.5,
    is_manual_override: true,
  };
});
const t6snap = snap(override, { translation: 10, ai_translation: 0, additional_service: 0 });
const t6 = await pdfText(await generateCommercialProposalPdf({ snapshot: t6snap }), "t6-override");
assert(t6.text.includes("9,50"), "T6 override 9.50 in PDF");
assert(!t6.text.includes("9,72"), "T6 calculated 9.72 not shown as final");

const frozen = structuredClone(t6snap);
frozen.lines[0]!.final_price = 99;
const later = await pdfText(await generateCommercialProposalPdf({ snapshot: t6snap }), "t7-frozen");
assert(later.text.includes("9,50"), "T7 original snapshot still 9.50");
assert(!later.text.includes("99,00"), "T7 mutated clone not used");

console.log(
  `verify-cp-ux-pdf: ok pages t2=${t2.pages} t3=${t3.pages} t4=${t4.pages} t5=${t5.pages} t6=${t6.pages}`,
);
